// Bakes an OpenStreetMap snapshot (saved from the app's "Save map data" button) into src/data/osm.js,
// so real roads, traffic signals and buildings load instantly and offline.
//   node scripts/bake-osm.mjs [data/osm-snapshot.json]
// Map data © OpenStreetMap contributors, available under the Open Database License (ODbL).
import fs from 'node:fs';

const src = process.argv[2] || 'data/osm-snapshot.json';
const json = JSON.parse(fs.readFileSync(src, 'utf8'));
const r5 = (v) => Math.round(v * 1e5) / 1e5;
const flat = (geom) => geom.flatMap((g) => [r5(g.lat), r5(g.lon)]);
const roads = [], buildings = [], pitches = [], signals = [];
let school = null;
for (const el of json.elements || []) {
  const t = el.tags || {};
  if (el.type === 'node' && t.highway === 'traffic_signals') { signals.push(r5(el.lat), r5(el.lon)); continue; }
  if (el.type !== 'way' || !el.geometry) continue;
  if (t.highway) roads.push({ n: t.name || t.ref || '', r: t.ref || '', k: t.highway, p: flat(el.geometry) });
  else if (t.building) {
    const h = parseFloat(t.height) || (parseFloat(t['building:levels']) || 0) * 3.6 || (t.building === 'house' ? 7 : 9);
    buildings.push({ h: Math.round(h * 10) / 10, t: t.building, p: flat(el.geometry) });
  } else if (t.leisure) pitches.push({ k: t.leisure, p: flat(el.geometry) });
  if (t.amenity === 'school' && /carolina day/i.test(t.name || '')) school = { n: t.name, p: flat(el.geometry) };
}
const out = { source: json.osm3s?.timestamp_osm_base || '', roads, buildings, pitches, signals, school };
fs.writeFileSync(new URL('../src/data/osm.js', import.meta.url),
  `// Generated by scripts/bake-osm.mjs from ${src} (OSM data as of ${out.source}).\n` +
  `// Map data © OpenStreetMap contributors, ODbL. Coordinates are flat [lat, lon, lat, lon, ...] arrays.\n` +
  `export const OSM = ${JSON.stringify(out)};\n`);
console.log(`roads ${roads.length}, buildings ${buildings.length}, pitches ${pitches.length}, signals ${signals.length / 2}, school ${!!school}`);
console.log(`size ${(fs.statSync(new URL('../src/data/osm.js', import.meta.url)).size / 1024).toFixed(0)} KB`);
