// Downloads real elevation data (AWS Terrain Tiles, "terrarium" encoding) for the
// area around Carolina Day School and bakes it into src/data/terrain.js.
//   node scripts/build-terrain.mjs
import { PNG } from 'pngjs';
import fs from 'node:fs';
import { CENTER, HALF_EXTENT_M, GRID } from '../src/geo-constants.js';

const ZOOM = 13;
const M_PER_DEG_LAT = 110574;
const M_PER_DEG_LON = 111320 * Math.cos(CENTER.lat * Math.PI / 180);

const lon2tx = (lon) => ((lon + 180) / 360) * 2 ** ZOOM;
const lat2ty = (lat) => {
  const r = lat * Math.PI / 180;
  return ((1 - Math.log(Math.tan(r) + 1 / Math.cos(r)) / Math.PI) / 2) * 2 ** ZOOM;
};

const latMin = CENTER.lat - HALF_EXTENT_M / M_PER_DEG_LAT;
const latMax = CENTER.lat + HALF_EXTENT_M / M_PER_DEG_LAT;
const lonMin = CENTER.lon - HALF_EXTENT_M / M_PER_DEG_LON;
const lonMax = CENTER.lon + HALF_EXTENT_M / M_PER_DEG_LON;

const tx0 = Math.floor(lon2tx(lonMin)), tx1 = Math.floor(lon2tx(lonMax));
const ty0 = Math.floor(lat2ty(latMax)), ty1 = Math.floor(lat2ty(latMin));

const tiles = new Map();
for (let tx = tx0; tx <= tx1; tx++) {
  for (let ty = ty0; ty <= ty1; ty++) {
    const url = `https://s3.amazonaws.com/elevation-tiles-prod/terrarium/${ZOOM}/${tx}/${ty}.png`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${url}: ${res.status}`);
    tiles.set(`${tx}/${ty}`, PNG.sync.read(Buffer.from(await res.arrayBuffer())));
    process.stdout.write('.');
  }
}
console.log(`\nfetched ${tiles.size} tiles`);

function samplePx(gx, gy) {
  const tx = Math.floor(gx / 256), ty = Math.floor(gy / 256);
  const png = tiles.get(`${tx}/${ty}`);
  const px = Math.min(255, Math.max(0, gx - tx * 256)), py = Math.min(255, Math.max(0, gy - ty * 256));
  const i = (py * 256 + px) * 4;
  return png.data[i] * 256 + png.data[i + 1] + png.data[i + 2] / 256 - 32768;
}
function sample(lat, lon) {
  const fx = lon2tx(lon) * 256 - 0.5, fy = lat2ty(lat) * 256 - 0.5;
  const x0 = Math.floor(fx), y0 = Math.floor(fy), ax = fx - x0, ay = fy - y0;
  const a = samplePx(x0, y0), b = samplePx(x0 + 1, y0), c = samplePx(x0, y0 + 1), d = samplePx(x0 + 1, y0 + 1);
  return (a * (1 - ax) + b * ax) * (1 - ay) + (c * (1 - ax) + d * ax) * ay;
}

const n = GRID + 1;
const out = new Uint16Array(n * n);
let lo = Infinity, hi = -Infinity;
for (let j = 0; j < n; j++) {
  // row 0 = north edge
  const z = -HALF_EXTENT_M + (2 * HALF_EXTENT_M * j) / GRID;
  const lat = CENTER.lat - z / M_PER_DEG_LAT;
  for (let i = 0; i < n; i++) {
    const x = -HALF_EXTENT_M + (2 * HALF_EXTENT_M * i) / GRID;
    const lon = CENTER.lon + x / M_PER_DEG_LON;
    const e = sample(lat, lon);
    lo = Math.min(lo, e); hi = Math.max(hi, e);
    out[j * n + i] = Math.round(e * 10); // decimeters
  }
}
const b64 = Buffer.from(out.buffer).toString('base64');
fs.writeFileSync(new URL('../src/data/terrain.js', import.meta.url),
  `// Generated by scripts/build-terrain.mjs from AWS Terrain Tiles (zoom ${ZOOM}).\n` +
  `// Source data: USGS 3DEP / SRTM via Mapzen terrarium tiles. Uint16 elevations in decimeters, row 0 = north.\n` +
  `export const TERRAIN_SIZE = ${n};\nexport const TERRAIN_B64 = "${b64}";\n`);
console.log(`grid ${n}x${n}, elevation ${lo.toFixed(1)}..${hi.toFixed(1)} m`);
const ci = (GRID / 2) | 0;
console.log(`elevation at school: ${(out[ci * n + ci] / 10).toFixed(1)} m`);
